config/routes.rb
Rails.application.routes.draw do

  get 'files/show'

  root "pages#home"

  get "logout", to: "sessions#destroy"

  resources :repositories, only: [:show]
  resources :commits, only: [:index, :show] do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :files, only: [:show]

  
  resources :users, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/comment.rb
class Comment
  def initialize(args*)
    @text = args[:text]
    @author = current_user.username
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, uniqueness: true
  validates :github_username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def github_authenticated?(user)
    client = get_client(user)
    begin
      client.user
    rescue => e
      puts "*" * 50
      p e
      puts "*" * 50
      return false
    end
    return true
  end

  def get_client(user = current_user || User.new)
    @client = Octokit::Client.new(:login => user.github_username, :password => user.github_password)
  end

  def require_login
    redirect_to "pages#home" unless logged_in?
  end

  private

  def logged_in?
    session[:user_id].present?
  end

  def current_user
    User.find(session[:user_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login
  before_action :get_client

  def new
  end

  def create
    sha = params[:commit_id]
    commit = @client.get("https://api.github.com/repos/dstavis/gitreview/commits/#{sha}")
    success = @client.post(commit.comments_url, {body: params[:body]})
    redirect_to commit_path(params[:commit_id])
  end

  def destroy
    success = @client.delete("https://api.github.com/repos/dstavis/gitreview/comments/#{params[:id]}")
    redirect_to commit_path(id: params[:commit_id])
  end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  before_action :require_login
  before_action :get_client

  # This is the same as a "repository"
  # TODO: Make the repository easy to change
  def index
    @commits = @client.get("https://api.github.com/repos/dstavis/gitreview/commits")
  end

  # This is a single commit
  def show
    sha = params[:id]
    commit = @client.get("https://api.github.com/repos/dstavis/gitreview/commits/#{sha}")
    @files = commit.files
    
    # (if any of the comments have author.username == current_user.username, they have a delete option)
    
    @comments = @client.get(commit.comments_url)
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_action :require_login
  before_action :get_client
  
  def show
    path = params[:id]
    binding.pry
    @file = @client.get("https://api.github.com/repos/dstavis/gitreview/contents/#{path}")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to controller: :commits, action: :index if logged_in?
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && params[:password] == user.password && github_authenticated?(user)
      session[:user_id] = user.id
      redirect_to controller: 'commits', action: 'index'
    else
      redirect_to controller: 'sessions', action: 'new'
    end
  end

  def destroy
    # logout
    session[:user_id] = nil
    redirect_to controller: 'pages', action: 'home'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_or_initialize_by(username: user_params[:username])
    user.update_attributes(user_params)
    if github_authenticated?(user)
      if user.save
        session[:user_id] = user.id
        redirect_to :controller => :commits, :action => :index
      else
        redirect_to action: :new
      end
    else
      redirect_to action: :new
    end
  end

  def destroy
    # Delete account
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :github_username, :github_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    current_user.present?
  end

  def current_user
    User.find(session[:user_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.slim
.container
  .col-md-12
    h1 New Comment

    = form_tag(commit_comments_path)
      = text_area_tag :body

      = submit_tag("Post")
      

app/views/commits/index.html.slim
.container

  - @commits.each do |commit|
    .row
      .col-md-1
        = link_to commit_path(id: commit.sha)
          = commit.sha.truncate(12)
      .col-md-8
        = commit.commit.message
      .col-md-3
        = commit.commit.author.name

app/views/commits/show.html.slim
.container

  .col-md-9
    h1 Files changed in this commit
    - @files.each do |file|
      .row
        .col-md-3
          = link_to file.filename, file.
        .col-md-6
        .col-md-3
          = file.sha.truncate(14)
      .row
        .col-md-1
        .col-md-11
          p== file.patch
    
    - if @comments.present?
      h1 Comments
      - @comments.each do |comment|
        .row
          .col-md-1
          .col-md-3
            = comment.user.login
          .col-md-2
            - if current_user.github_username == comment.user.login
              = button_to "Delete", commit_comment_path(commit_id: params[:id], id: comment.id), :method => :delete, class: "btn btn-danger"
        .row
          .col-md-2
          .col-md-10
            p= comment.body
    - else
      h1 No comments
    
    = link_to "Make a New Comment", new_commit_comment_path(commit_id: params[:id]), class: "btn btn-default"

app/views/files/show.html.slim
.container
  .row
    .col-md-2
      =@file.filename
  .row
    .col-md-12
      p== @file.patch

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gitreview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/commit.html.slim
.container

  .col-md-9
    - @files.each do |file|
      .row
        .col-md-3
          = file.filename
        .col-md-6
          = file.path
        .col-md-3
          = link_to file_path, params.merge({:sha => file.sha})
            = file.sha.truncate(14)
      .row
        .col-md-12
          p= file.patch
    - @comments.each do |comment|
      .row
        .col-md-3
          = comment.author.name
      .row
        .col-md-12
          p= comment.text

app/views/pages/home.html.slim
.container
  .col-md-9
    h1 Welcome to Gitreview! v0.1.0 (functionally complete/ugly)
    
    .col-md-3
      .signup
        p Are you new here?
        a href=new_user_path class="btn btn-default"
          | Sign up
    .col-md-3
      .signin
        p Already have an account?
        a href=new_session_path class="btn btn-default"
          | Sign in

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim

app/views/users/destroy.html.slim
h1 Users#destroy
p Find me in app/views/users/destroy.html.slim

app/views/users/new.html.slim
h1 Please create an account

= form_for @user do |f|
  
  = f.label :username
  = f.text_field :username

  = f.label :password
  = f.text_field :password

  = f.label :github_username
  = f.text_field :github_username

  = f.label :github_password
  = f.text_field :github_password

  = f.submit